glm.fit <- glm(TARGET~OCCUPATION_TYPE+NAME_INCOME_TYPE+REGION_RATING_CLIENT_W_CITY+NAME_EDUCATION_TYPE+ORGANIZATION_TYPE
    +CNT_CHILDREN+AMT_INCOME_TOTAL+AMT_CREDIT+AMT_ANNUITY+AMT_GOODS_PRICE+REGION_POPULATION_RELATIVE+CNT_FAM_MEMBERS+
      HOUR_APPR_PROCESS_START+EXT_SOURCE_2+EXT_SOURCE_3+OBS_30_CNT_SOCIAL_CIRCLE+DEF_30_CNT_SOCIAL_CIRCLE+
      OBS_60_CNT_SOCIAL_CIRCLE+DEF_60_CNT_SOCIAL_CIRCLE+AMT_REQ_CREDIT_BUREAU_HOUR+AMT_REQ_CREDIT_BUREAU_DAY+
      AMT_REQ_CREDIT_BUREAU_WEEK+AMT_REQ_CREDIT_BUREAU_MON+AMT_REQ_CREDIT_BUREAU_QRT+AMT_REQ_CREDIT_BUREAU_YEAR+
      MISSING_RATIO+YEARS_BIRTH+YEARS_EMPLOYED+YEARS_REGISTRATION+YEARS_ID_PUBLISH+YEARS_LAST_PHONE_CHANGE+SUM_FLAG_DOCUMENT+
      SUM_AMT_REQ_CREDIT_BUREAU+NAME_CONTRACT_TYPE+CODE_GENDER+FLAG_OWN_CAR+FLAG_OWN_REALTY+NAME_TYPE_SUITE+
      NAME_FAMILY_STATUS+NAME_HOUSING_TYPE+FLAG_EMP_PHONE+FLAG_WORK_PHONE+FLAG_CONT_MOBILE+FLAG_PHONE
    +FLAG_EMAIL+OCCUPATION_TYPE+REGION_RATING_CLIENT+WEEKDAY_APPR_PROCESS_START+
      REG_REGION_NOT_LIVE_REGION+REG_REGION_NOT_WORK_REGION+LIVE_REGION_NOT_WORK_REGION+REG_CITY_NOT_LIVE_CITY+REG_CITY_NOT_WORK_CITY+
      LIVE_CITY_NOT_WORK_CITY+FLAG_DOCUMENT_2+FLAG_DOCUMENT_3+FLAG_DOCUMENT_4+FLAG_DOCUMENT_5+FLAG_DOCUMENT_6+
      FLAG_DOCUMENT_7+FLAG_DOCUMENT_8+FLAG_DOCUMENT_9+FLAG_DOCUMENT_10+FLAG_DOCUMENT_11+FLAG_DOCUMENT_12+FLAG_DOCUMENT_13+
      FLAG_DOCUMENT_14+FLAG_DOCUMENT_15+FLAG_DOCUMENT_16+FLAG_DOCUMENT_17+FLAG_DOCUMENT_18+FLAG_DOCUMENT_19+FLAG_DOCUMENT_20+
      FLAG_DOCUMENT_21,
    data=filter_data_loan,family=binomial) #訓練模型

summary(glm.fit)

pre_respon<-predict(glm.fit, newdata = filter_data_loan_test, type ='response') #這裡放入新的資料

#--- 藉由上述程式調整需要切點再生成應變數
predicted_data <- factor(ifelse(pre_respon > 0.13, 1, 0), levels = c("0", "1")) # 挑 0.13 或 0.14 
filter_data_loan_test <- filter_data_loan_test %>%
  mutate(PRED_TARGET = predicted_data)

